# Nixpacks configuration for Railway
# Force Node.js provider instead of Next.js detection

[phases.setup]
nixPkgs = ["nodejs_20", "npm"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["echo 'Bot uses tsx runtime - no build required'"]

[start]
cmd = "npm run start:bot"
