[build]
builder = "nixpacks"
buildCommand = "echo 'No build needed for bot - uses tsx runtime'"

[deploy]
startCommand = "npm run start:bot"
restartPolicyType = "always"
restartPolicyMaxRetries = 10

[env]
# Railway will auto-inject DATABASE_URL, RAILWAY_ENVIRONMENT, etc.
# Add your custom env vars in Railway dashboard
